/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author LUCYLEONOR
 */
import clases.*;
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    
    Cuenta c1,c2 = null;
    public Principal() {
        initComponents();
        cmdMostrar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNumeroDeCuenta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        cmbOp = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        cmdCalcular = new javax.swing.JButton();
        cmdLimpiar = new javax.swing.JButton();
        cmdMostrar = new javax.swing.JButton();
        cmdActualizarSaldo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtInteresAnual = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cuenta");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Cuenta");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Num. Cuenta");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        txtNumeroDeCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroDeCuentaKeyTyped(evt);
            }
        });
        jPanel1.add(txtNumeroDeCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 70, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Identificacion");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        txtIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdentificacionKeyTyped(evt);
            }
        });
        jPanel1.add(txtIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 70, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 17, 420, 160));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 440, 190));

        cmbOp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingresar Saldo", "Retirar" }));
        jPanel1.add(cmbOp, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 150, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Optiones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdCalcular.setText("Efectuar Opcion");
        cmdCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalcularActionPerformed(evt);
            }
        });
        jPanel3.add(cmdCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 120, -1));

        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 120, -1));

        cmdMostrar.setText("Mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 120, -1));

        cmdActualizarSaldo.setText("Actualizar Saldo");
        cmdActualizarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdActualizarSaldoActionPerformed(evt);
            }
        });
        jPanel3.add(cmdActualizarSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 120, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 140, 220));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Saldo Actual");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        txtSaldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSaldoKeyTyped(evt);
            }
        });
        jPanel1.add(txtSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 100, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Interes Anual");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        txtInteresAnual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInteresAnualKeyTyped(evt);
            }
        });
        jPanel1.add(txtInteresAnual, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 80, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 480));

        setSize(new java.awt.Dimension(654, 519));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalcularActionPerformed

        if (txtIdentificacion.getText().trim().isEmpty() && txtNumeroDeCuenta.getText().trim().isEmpty() && txtSaldo.getText().trim().isEmpty() && txtInteresAnual.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Ingrese Los Datos","Error",2);
            txtNumeroDeCuenta.requestFocusInWindow();
        }
        else if (txtIdentificacion.getText().trim().isEmpty()) {
             Helper.mensaje(this, "Ingrese El Numero De Identificacion","Error",2);
            txtIdentificacion.requestFocusInWindow();
        }
        else if (txtNumeroDeCuenta.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Ingrese El Numero De Cuenta","Error",2);
            txtNumeroDeCuenta.requestFocusInWindow();
        }
        else if (txtSaldo.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Ingrese El Saldo Actual De La Cuenta","Error",2);
            txtSaldo.requestFocusInWindow();
        }
        else if (txtInteresAnual.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Ingrese El Interes Anual De La Cuenta","Error",2);
            txtInteresAnual.requestFocusInWindow();
        }
        else{
        txtResultado.setText("");
        int op, identificacion,cuenta;
        long saldo;
        int interes;
        identificacion = Integer.parseInt(txtIdentificacion.getText());
        cuenta = Integer.parseInt(txtNumeroDeCuenta.getText());
        saldo =  Long.parseLong(txtSaldo.getText());
        interes = Integer.parseInt(txtInteresAnual.getText());
       
        op = cmbOp.getSelectedIndex();
      
        c1 = new Cuenta (cuenta,identificacion,saldo,interes);
         
        
        switch (op){
            case 0:
            c2 = c1.ingresar().actualizarsaldo();
            break;
            case 1:
            c2 = c1.retirar().actualizarsaldo();
            break;
            
        }
        
        }
    }//GEN-LAST:event_cmdCalcularActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed

        txtIdentificacion.setText("");
        txtInteresAnual.setText("");
        txtNumeroDeCuenta.setText("");
        txtResultado.setText("");
        txtSaldo.setText("");
        cmdActualizarSaldo.setEnabled(true);
        txtNumeroDeCuenta.requestFocusInWindow();
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed

        if (txtIdentificacion.getText().trim().isEmpty() && txtNumeroDeCuenta.getText().trim().isEmpty() && txtSaldo.getText().trim().isEmpty() && txtInteresAnual.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Ingrese Los Datos","Error",2);
            txtNumeroDeCuenta.requestFocusInWindow();
        }
        else if (txtIdentificacion.getText().trim().isEmpty()) {
             Helper.mensaje(this, "Ingrese El Numero De Identificacion","Error",2);
            txtIdentificacion.requestFocusInWindow();
        }
        else if (txtNumeroDeCuenta.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Ingrese El Numero De Cuenta","Error",2);
            txtNumeroDeCuenta.requestFocusInWindow();
        }
        else if (txtSaldo.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Ingrese El Saldo Actual De La Cuenta","Error",2);
            txtSaldo.requestFocusInWindow();
        }
        else if (txtInteresAnual.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Ingrese El Interes Anual De La Cuenta","Error",2);
            txtInteresAnual.requestFocusInWindow();
        }
        else {
        txtResultado.setText("");
        txtResultado.append("Identificacion: " + c2.getIdentificacion() + "\n"
                + "Numero De Cuenta: " + c2.getNumerodecuenta() + "\n"
                + "Saldo Actual: " + c2.getSaldoactual() + "\n"
                + "Interes Anual: " + c2.getInteresanual());
        }
        cmdActualizarSaldo.setEnabled(true);

    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void txtNumeroDeCuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroDeCuentaKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();

        }
    }//GEN-LAST:event_txtNumeroDeCuentaKeyTyped

    private void txtSaldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldoKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();

        }
    }//GEN-LAST:event_txtSaldoKeyTyped

    private void txtInteresAnualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInteresAnualKeyTyped
       char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();

        }
    }//GEN-LAST:event_txtInteresAnualKeyTyped

    private void txtIdentificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentificacionKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();

        }
    }//GEN-LAST:event_txtIdentificacionKeyTyped

    private void cmdActualizarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdActualizarSaldoActionPerformed

        if (txtIdentificacion.getText().trim().isEmpty() && txtNumeroDeCuenta.getText().trim().isEmpty() && txtSaldo.getText().trim().isEmpty() && txtInteresAnual.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Ingrese Los Datos","Error",2);
            txtNumeroDeCuenta.requestFocusInWindow();
        }
        else if (txtIdentificacion.getText().trim().isEmpty()) {
             Helper.mensaje(this, "Ingrese El Numero De Identificacion","Error",2);
            txtIdentificacion.requestFocusInWindow();
        }
        else if (txtNumeroDeCuenta.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Ingrese El Numero De Cuenta","Error",2);
            txtNumeroDeCuenta.requestFocusInWindow();
        }
        else if (txtSaldo.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Ingrese El Saldo Actual De La Cuenta","Error",2);
            txtSaldo.requestFocusInWindow();
        }
        else if (txtInteresAnual.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Ingrese El Interes Anual De La Cuenta","Error",2);
            txtInteresAnual.requestFocusInWindow();
        }
        else {
        int op, identificacion,cuenta;
        long saldo;
        int interes;
        identificacion = Integer.parseInt(txtIdentificacion.getText());
        cuenta = Integer.parseInt(txtNumeroDeCuenta.getText());
        saldo =  Long.parseLong(txtSaldo.getText());
        interes = Integer.parseInt(txtInteresAnual.getText());
       
        op = cmbOp.getSelectedIndex();
      
        c1 = new Cuenta (cuenta,identificacion,saldo,interes);

        c2 = c1.actualizarsaldo();
        txtResultado.setText("");
        txtResultado.append("Identificacion: " + c2.getIdentificacion() + "\n"
                + "Numero De Cuenta: " + c2.getNumerodecuenta() + "\n"
                + "Saldo Actual: " + c2.getSaldoactual() + "\n"
                + "Interes Anual: " + c2.getInteresanual());
        cmdActualizarSaldo.setEnabled(false);
        }
        
        cmdMostrar.setEnabled(true);
    }//GEN-LAST:event_cmdActualizarSaldoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbOp;
    private javax.swing.JButton cmdActualizarSaldo;
    private javax.swing.JButton cmdCalcular;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtInteresAnual;
    private javax.swing.JTextField txtNumeroDeCuenta;
    private javax.swing.JTextArea txtResultado;
    private javax.swing.JTextField txtSaldo;
    // End of variables declaration//GEN-END:variables
}
