/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author LUCYLEONOR
 */
import clases.*;
import javax.swing.JOptionPane;

public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    Cuenta c;

    public Principal() {
        initComponents();
        txtInteresAnual.setEnabled(false);
        cmdMostrar.setEnabled(false);
        cmdActualizarSaldo.setEnabled(false);
        txtIngreso.setEnabled(false);
        txtEgreso.setEnabled(false);
        cmdIngresar.setEnabled(false);
        cmdRetirar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNumeroDeCuenta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        cmdLimpiar = new javax.swing.JButton();
        cmdCrear = new javax.swing.JButton();
        cmdMostrar = new javax.swing.JButton();
        cmdActualizarSaldo = new javax.swing.JButton();
        cmdIngresar = new javax.swing.JButton();
        cmdRetirar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtInteresAnual = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtIngreso = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEgreso = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cuenta");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Cuenta");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Num. Cuenta");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        txtNumeroDeCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroDeCuentaKeyTyped(evt);
            }
        });
        jPanel1.add(txtNumeroDeCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 70, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Identificacion");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        txtIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdentificacionKeyTyped(evt);
            }
        });
        jPanel1.add(txtIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 70, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResultado.setEditable(false);
        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 17, 420, 160));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 440, 190));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Optiones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 120, -1));

        cmdCrear.setText("Crear Cuenta");
        cmdCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearActionPerformed(evt);
            }
        });
        jPanel3.add(cmdCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 120, -1));

        cmdMostrar.setText("Mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 120, -1));

        cmdActualizarSaldo.setText("Actualizar Saldo");
        cmdActualizarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdActualizarSaldoActionPerformed(evt);
            }
        });
        jPanel3.add(cmdActualizarSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 120, -1));

        cmdIngresar.setText("Ingresar");
        cmdIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdIngresarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 120, -1));

        cmdRetirar.setText("Retirar");
        cmdRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRetirarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 120, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 140, 320));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Saldo Actual");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        txtSaldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSaldoKeyTyped(evt);
            }
        });
        jPanel1.add(txtSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 100, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Interes Anual");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));
        jPanel1.add(txtInteresAnual, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 80, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Ingreso");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        txtIngreso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIngresoKeyTyped(evt);
            }
        });
        jPanel1.add(txtIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 100, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Egreso");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, -1));

        txtEgreso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEgresoKeyTyped(evt);
            }
        });
        jPanel1.add(txtEgreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 100, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 440));

        setSize(new java.awt.Dimension(675, 494));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed

        txtIdentificacion.setText("");
        txtNumeroDeCuenta.setText("");
        txtResultado.setText("");
        txtSaldo.setText("");
        txtInteresAnual.setText("");
        txtIngreso.setText("");
        txtEgreso.setText("");
        txtInteresAnual.setEnabled(false);
        txtIdentificacion.setEditable(true);
        txtNumeroDeCuenta.setEditable(true);
        txtSaldo.setEditable(true);
        cmdMostrar.setEnabled(false);
        cmdCrear.setEnabled(false);
         txtIngreso.setEnabled(false);
        txtEgreso.setEnabled(false);
        txtNumeroDeCuenta.requestFocusInWindow();
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    private void txtNumeroDeCuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroDeCuentaKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();

        }
    }//GEN-LAST:event_txtNumeroDeCuentaKeyTyped

    private void txtSaldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldoKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();

        }
    }//GEN-LAST:event_txtSaldoKeyTyped

    private void txtIdentificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentificacionKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();

        }
    }//GEN-LAST:event_txtIdentificacionKeyTyped

    private void cmdCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearActionPerformed

        if (txtIdentificacion.getText().trim().isEmpty() && txtNumeroDeCuenta.getText().trim().isEmpty() && txtSaldo.getText().trim().isEmpty() && txtInteresAnual.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Ingrese Los Datos", "Error", 2);
            txtNumeroDeCuenta.requestFocusInWindow();
        } else if (txtIdentificacion.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Ingrese El Numero De Identificacion", "Error", 2);
            txtIdentificacion.requestFocusInWindow();
        } else if (txtNumeroDeCuenta.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Ingrese El Numero De Cuenta", "Error", 2);
            txtNumeroDeCuenta.requestFocusInWindow();
        } else if (txtSaldo.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Ingrese El Saldo Actual De La Cuenta", "Error", 2);
            txtSaldo.requestFocusInWindow();
        } else {
            txtResultado.setText("");
            int op, sw = 1;
            long cuenta = 0, identificacion = 0;
            double saldo;
            try {
                identificacion = Long.parseLong(txtIdentificacion.getText());
            } catch (NumberFormatException e) {
                Helper.mensaje(this, "Solo Se Permite Un Limite de 18 Digitos En La Identificacion", "Error", 2);
                sw = 0;
            }
            try {
                cuenta = Long.parseLong(txtNumeroDeCuenta.getText());
            } catch (NumberFormatException e) {
                Helper.mensaje(this, "Solo Se Permite Un Limite de 18 Digitos En El Numero De cuenta", "Error", 2);
                sw = 0;
            }
            if (sw == 1) {

                saldo = Double.parseDouble(txtSaldo.getText());

                c = new Cuenta(cuenta, identificacion, saldo);
                Helper.mensaje(this, "Cuenta Creada Satisfactoriamente, su saldo actual es: "+c.getSaldo_actual(), "Cuenta Creada", 1);

                txtInteresAnual.setEnabled(true);
                txtIdentificacion.setEditable(false);
                txtNumeroDeCuenta.setEditable(false);
                txtSaldo.setEditable(false);
                cmdCrear.setEnabled(false);
                cmdActualizarSaldo.setEnabled(true);
                cmdMostrar.setEnabled(false);
            }
        }
    }//GEN-LAST:event_cmdCrearActionPerformed

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed

        txtResultado.setText("");
        String aux;
        aux = c.mostrar();
        txtResultado.append(aux);
        cmdMostrar.setEnabled(false);

    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void cmdActualizarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdActualizarSaldoActionPerformed

        txtResultado.setText("");
        double ian = 0, sw = 1;
        if (txtInteresAnual.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Ingrese El Interes Anual", "Error", 2);
            txtInteresAnual.requestFocusInWindow();
        } else {
            try {
                ian = Double.parseDouble(txtInteresAnual.getText());
            } catch (NumberFormatException e) {
                Helper.mensaje(this, "Ingrese Un Dato Valido", "Error", 2);
                txtInteresAnual.requestFocusInWindow();
                txtInteresAnual.selectAll();
                sw = 0;
            }
            if (sw == 1) {

                c.actulizarSaldo(ian);
                cmdMostrar.setEnabled(true);
                txtIngreso.setEnabled(true);
                txtEgreso.setEnabled(true);
                cmdIngresar.setEnabled(true);
                cmdRetirar.setEnabled(true);
            }
        }
    }//GEN-LAST:event_cmdActualizarSaldoActionPerformed

    private void cmdRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRetirarActionPerformed

        txtResultado.setText("");
        if (txtEgreso.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Ingrese el dinero a retirar", "Error", 2);
            txtEgreso.requestFocusInWindow();
        } else if (c.getSaldo_actual() == 0) {
            Helper.mensaje(this, "Usted no tiene saldo", "Error", 2);
            txtEgreso.requestFocusInWindow();
            txtEgreso.selectAll();
        } else if (Integer.parseInt(txtEgreso.getText()) > c.getSaldo_actual()) {
            Helper.mensaje(this, "Fondos insuficientes", "Error", 2);
            txtEgreso.requestFocusInWindow();
            txtEgreso.selectAll();
        } else {

            int Egreso, res, sw = 1;
            Egreso = Integer.parseInt(txtEgreso.getText());
            res = Helper.mensaje(this, "¿Desea retirar " + Egreso + "$" + " de su cuenta?", "Retiro", 3);
            if (res == 0) {
                sw = 1;
            } else {
                sw = 0;
            }
            if (sw == 1) {
                c.retirar(Egreso);
                Helper.mensaje(this, "Usted retiro: " + Egreso + "$" + "\nSu nuevo saldo es: " + c.getSaldo_actual() + "$", "Saldo Actual", 1);
                txtEgreso.setText("");
            }
        }

    }//GEN-LAST:event_cmdRetirarActionPerformed

    private void cmdIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdIngresarActionPerformed

        txtResultado.setText("");
        if (txtIngreso.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Ingrese el dinero a consignar", "Error", 2);
            txtIngreso.requestFocusInWindow();
        } else {
            int Ingreso, sw = 1, res;
            Ingreso = Integer.parseInt(txtIngreso.getText());
            res = Helper.mensaje(this, "¿Desea ingresar " + Ingreso + "$" + " a su cuenta?", "Ingreso", 3);
            if (res == 0) {
                sw = 1;
            } else {
                sw = 0;
            }
            if (sw == 1) {
                c.ingresar(Ingreso);
                Helper.mensaje(this, "Usted ingresó: " + Ingreso + "$" + "\nSu nuevo saldo es: " + c.getSaldo_actual() + "$", "Saldo Actual", 1);
                txtIngreso.setText("");
            }
        }


    }//GEN-LAST:event_cmdIngresarActionPerformed

    private void txtIngresoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIngresoKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();

        }
    }//GEN-LAST:event_txtIngresoKeyTyped

    private void txtEgresoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEgresoKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();

        }
    }//GEN-LAST:event_txtEgresoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdActualizarSaldo;
    private javax.swing.JButton cmdCrear;
    private javax.swing.JButton cmdIngresar;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JButton cmdRetirar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtEgreso;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtIngreso;
    private javax.swing.JTextField txtInteresAnual;
    private javax.swing.JTextField txtNumeroDeCuenta;
    private javax.swing.JTextArea txtResultado;
    private javax.swing.JTextField txtSaldo;
    // End of variables declaration//GEN-END:variables
}
